### ISSUE TITLE
[sirius-hla-si-ma-control.py] application dies.

### ISSUE THREAD

**Issue by xresende** [lnls-sirius/hla#17]
When trying to turn all quads on on the quadrupole tab.

error message:

Traceback (most recent call last):
  File "/home/fac_files/lnls-sirius/hla/pyqt-apps/siriushla/as_ma_control/control_widget/BaseMagnetControlWidget.py", line 104, in <lambda>
    turn_on.triggered.connect(lambda: self.pwrstate_action(True))
  File "/home/fac_files/lnls-sirius/hla/pyqt-apps/siriushla/as_ma_control/control_widget/BaseMagnetControlWidget.py", line 83, in pwrstate_action
    widget.pwrstate_button.send_value(state)
TypeError: send_value() takes 1 positional argument but 2 were given
Aborted (core dumped)

**Comment by gu1lhermelp** [comment]
Done

**Comment by xresende** [comment]
tested.
